version: '2.1'

services:
  frontend:
    build: frontend/.
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend

  backend:
    build: backend/.
    ports:
      - "4000:4000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/api/products" ]
      interval: 30s
      timeout: 10s
      retries: 5
