version: "3"
services:
  frontend:
    # image: frontend
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  backend:
    # image: backend
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
