version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - database
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app-network
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ahmed
      - MONGO_INITDB_ROOT_PASSWORD=ahmed
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
